### PR TITLE
Compatibility with Rails 4

### PR DESCRIPTION
**Pull request by juanboca**
Its working fine :)

### CODE REVIEW

**Comment by tboerger** [comment]
What about this pull request? I really need this gem for my rails 4 application :(

**Comment by andruby** [comment]
@tboerger you can use this branch in Rails 4. I don't know if @nubis is still maintaining this gem.

**Comment by tboerger** [comment]
This is not an option as i have to package all dependencies. I will integrate the code fixed into the rails application.

**Comment by nubis** [comment]
Hi Guys, 

I'm sorry, as @andruby  says I'm a bit buys to maintain this gem, and for newer projects I moved back to yaml-like translation backends so I cannot include the workflow as part of my daily job. If anyone wants to take over I can make you admins or point to any fork of this repo on the main readme file. I could just merge this pull request but apparently the build failed in Travis. I can also pass ownership of the gem name in rubygems so that other people can start packaging and publishing new versions.
Just let me know if any of you are interested.

**Comment by tboerger** [comment]
I would like to take ver the gem. I would move it to the webhippie github org. I will fork it.

**Comment by tboerger** [comment]
I have forked po_to_json as well.

**Comment by juanboca** [comment]
Hi @nubis. Thanks for merging my changes. I can take over and fix te build issues (very simple). If you want to make me admin of this repo it will be fine. 
I'm now on vacations, but as soon as I return to work in a few weeks I'll be available to do anything necessary to continue with this gem.

**Comment by nubis** [comment]
Hi juan, I'm in the process of moving ownership of this repo to Thomas
Boerger, I'll be glad to merge any further changes you have that would fix
the build, I'll make you an admin.

Cheers!

**Comment by tboerger** [comment]
@nubis if you make me an admin i'm pretty sure that i can transfer the ownership.

**Comment by tboerger** [comment]
@juanboca The repos are moved now. I think we get some updates within the next weeks :)
@nubis Thank you!

I will review the forks of this gem as well to get some changes from the forks back into the codebase.

**Comment by nubis** [comment]
Awesome! Wish you guys the best, and sorry for bailing out :)

**Pull request merged**
